# Merging Survey and Platform Data -  Group with Randomization

Completely done in Python. There ore no steps required in Excel

v1_28.03.2024

In [11]:
import pandas as pd

In [14]:
# Load the first dataset
df1 = pd.read_csv('data_prep_validation2_pre-merge_survey.csv',  sep=';')

# Load the second dataset
df2 = pd.read_csv('data_prep_cleaned_platform.csv',  sep=';')

In [15]:
# Merge the datasets on 'VPNCode'
merged_df = pd.merge(df1, df2[['VPNCode', 'group_nr']], on='VPNCode', how='inner')

In [16]:
# Treat 'group_nr' as a categorical variable
merged_df['group_nr'] = merged_df['group_nr'].astype('category')

In [17]:
merged_df.head()

,VPNCode,AILiteracy[Use1],AILiteracy[Use2],AILiteracy[Use3],AILiteracy[Use4],AILiteracy[Use5],AILiteracy[Use6],AILiteracy[Kno1],AILiteracy[Kno2],AILiteracy[Kno3],...,NEO[E],NEO[A],NEO[C],NEO[N],NEO[O],JC1[IStR],JC1[HRJD],JC2[IStR],JC2[HRJD],group_nr
0,AHO1006,4,5,4,5,5,5,5,4,5,...,3.00,4.00,3.75,1.75,3.4,2.4,2.333333,2.8,5.00,2
1,AWA2505,4,4,3,4,4,4,2,4,2,...,2.50,2.50,3.50,2.75,4.0,3.4,2.000000,3.2,4.50,2
2,EZA0703,4,5,5,5,3,3,4,3,4,...,3.25,3.00,3.50,3.00,3.8,4.2,4.333333,3.8,2.00,5
3,AGU2207,5,4,4,4,4,4,4,2,3,...,3.00,2.75,3.25,3.75,4.0,3.6,3.666667,3.0,2.25,7
4,NPR1810,4,4,3,4,3,3,4,4,2,...,3.25,3.75,4.00,2.75,4.0,2.8,2.666667,3.6,1.50,7

In [18]:
# Save DF in a new CSV-File 
merged_df.to_csv('data_prep_validation2.csv', index=False, encoding='utf-8-sig', sep=',')